docs:
  items:
    - name: Local Workspace
      items:
        - path: ./docs
          name: Docs Atlas
        - path: ../another-project/docs
          name: Another Project
    - name: AI
      items:
        - name: Services
          items:
            - path: /Users/lx/ai-agent-server/docs
              name: AI-Agent
